jwt_get:nord_bot:
  variables:
    VAULT_ROLE: 'nord_bot'
    VAULT_KV_PATH: 'crosser/nord_bot/dev/env'
    VAULT_MAP_PARAMS: " "
  extends:
    - .jwt_get

docker:build:dev:
  rules:
    - if: $CI_COMMIT_REF_NAME == "dev" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: always
    - when: never
  extends:
    - .build_template

docker:deploy_app:dev:
  rules:
    - if: $CI_COMMIT_REF_NAME == "dev" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: always
    - when: never  
  cache:
    key: vault-env-${CI_COMMIT_SHORT_SHA}
    paths: 
      - ./${VAULT_FILENAME}
    policy: pull
  extends:
    - .deploy_app_template

jwt_remove:
  extends:
    - .jwt_remove
