jwt_get:crossing_spare:
  variables:
    VAULT_ROLE: 'crossing_spare'
    VAULT_KV_PATH: 'crosser/crossing_spare/prod/env'
    VAULT_MAP_PARAMS: " "
  extends:
    - .jwt_get

docker:build:prod:
  stage: 'build'
  rules:
    - if: $CI_COMMIT_REF_NAME == "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: always
    - when: never
  extends:
    - .build_template

docker:deploy_app:prod:
  rules:
    - if: $CI_COMMIT_REF_NAME == "main" && $CI_PIPELINE_SOURCE != "merge_request_event"
      when: always
    - when: never  
  cache:
    key: vault-env-${CI_COMMIT_SHORT_SHA}
    paths: 
      - ./${VAULT_FILENAME}
  extends:
    - .deploy_app_template
