"""Add places models, add ref

Revision ID: 1eb9af865b8c
Revises: 7afb81467e50
Create Date: 2024-09-09 17:28:17.812002

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1eb9af865b8c'
down_revision: Union[str, None] = '7afb81467e50'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('places',
    sa.Column('id', sa.Integer(), autoincrement=True, nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('name')
    )
    op.add_column('customers', sa.Column('referal_id', sa.Integer(), nullable=True))
    op.add_column('customers', sa.Column('place_id', sa.Integer(), nullable=True))
    op.alter_column('customers', 'id',
               existing_type=sa.BIGINT(),
               type_=sa.Integer(),
               existing_nullable=False,
               autoincrement=True)
    op.alter_column('customers', 'telegram_id',
                    existing_type=sa.VARCHAR(),
                    type_=sa.BigInteger(),
                    nullable=False,
                    postgresql_using='telegram_id::bigint')
    op.alter_column('customers', 'qresto_id',
               existing_type=sa.INTEGER(),
               nullable=False)
    op.alter_column('customers', 'news',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.create_foreign_key(None, 'customers', 'places', ['place_id'], ['id'])
    op.create_foreign_key(None, 'customers', 'customers', ['referal_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.drop_constraint(None, 'customers', type_='foreignkey')
    op.alter_column('customers', 'news',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    op.alter_column('customers', 'qresto_id',
               existing_type=sa.INTEGER(),
               nullable=True)
    op.alter_column('customers', 'telegram_id',
                    existing_type=sa.BigInteger(),
                    type_=sa.VARCHAR(),
                    nullable=True)
    op.alter_column('customers', 'id',
               existing_type=sa.Integer(),
               type_=sa.BIGINT(),
               existing_nullable=False,
               autoincrement=True)
    op.drop_column('customers', 'place_id')
    op.drop_column('customers', 'referal_id')
    op.drop_table('places')
    # ### end Alembic commands ###
