"""phone str->bigint

Revision ID: c662be07de31
Revises: 1eb9af865b8c
Create Date: 2024-09-09 18:10:46.722426

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c662be07de31'
down_revision: Union[str, None] = '1eb9af865b8c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'phone_number',
               existing_type=sa.VARCHAR(),
               type_=sa.BigInteger(),
               existing_nullable=True,
               postgresql_using='phone_number::bigint')
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('customers', 'phone_number',
               existing_type=sa.BigInteger(),
               type_=sa.VARCHAR(),
               existing_nullable=True)
    # ### end Alembic commands ###
